// Generated by rust-bindgen 0.70.1 from src/c_src/re.h.
// To regenerate: bindgen src/c_src/re.h --use-core \
//   --allowlist-type regex_t --allowlist-function re_compile --allowlist-function re_matchp

#[repr(C)]
#[derive(Copy, Clone)]
pub struct regex_t {
    pub type_: ::core::ffi::c_uchar,
    pub u: regex_t__bindgen_ty_1,
}

#[repr(C)]
#[derive(Copy, Clone)]
pub union regex_t__bindgen_ty_1 {
    pub ch: ::core::ffi::c_uchar,
    pub ccl: usize,
}

pub type re_t = *const regex_t;

extern "C" {
    pub fn re_compile(
        re_compiled: *mut regex_t,
        size: usize,
        ccl_buf: *mut ::core::ffi::c_uchar,
        ccl_size: usize,
        pattern: *const ::core::ffi::c_char,
    ) -> usize;
}

extern "C" {
    pub fn re_matchp(
        pattern: re_t,
        ccl_buf: *const ::core::ffi::c_uchar,
        text: *const ::core::ffi::c_char,
        matchlength: *mut ::core::ffi::c_int,
        memo: *mut ::core::ffi::c_uchar,
        memo_bytes: usize,
        memo_stride: usize,
    ) -> ::core::ffi::c_int;
}
