name: Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: make coverage
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html/
